/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as FeedIndexRouteImport } from './routes/feed/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as PhotoPhotoIdRouteImport } from './routes/photo/$photoId'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as FeedPhotoPhotoIdRouteImport } from './routes/feed/photo/$photoId'
import { Route as _authSignInSplatRouteImport } from './routes/__auth/sign-in.$'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoPhotoIdRoute = PhotoPhotoIdRouteImport.update({
  id: '/photo/$photoId',
  path: '/photo/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedPhotoPhotoIdRoute = FeedPhotoPhotoIdRouteImport.update({
  id: '/feed/photo/$photoId',
  path: '/feed/photo/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const _authSignInSplatRoute = _authSignInSplatRouteImport.update({
  id: '/__auth/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs/$': typeof DocsSplatRoute
  '/photo/$photoId': typeof PhotoPhotoIdRoute
  '/docs/': typeof DocsIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sign-in/$': typeof _authSignInSplatRoute
  '/feed/photo/$photoId': typeof FeedPhotoPhotoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs/$': typeof DocsSplatRoute
  '/photo/$photoId': typeof PhotoPhotoIdRoute
  '/docs': typeof DocsIndexRoute
  '/feed': typeof FeedIndexRoute
  '/products': typeof ProductsIndexRoute
  '/sign-in/$': typeof _authSignInSplatRoute
  '/feed/photo/$photoId': typeof FeedPhotoPhotoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs/$': typeof DocsSplatRoute
  '/photo/$photoId': typeof PhotoPhotoIdRoute
  '/docs/': typeof DocsIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/__auth/sign-in/$': typeof _authSignInSplatRoute
  '/feed/photo/$photoId': typeof FeedPhotoPhotoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/docs/$'
    | '/photo/$photoId'
    | '/docs/'
    | '/feed/'
    | '/products/'
    | '/sign-in/$'
    | '/feed/photo/$photoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/docs/$'
    | '/photo/$photoId'
    | '/docs'
    | '/feed'
    | '/products'
    | '/sign-in/$'
    | '/feed/photo/$photoId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/docs/$'
    | '/photo/$photoId'
    | '/docs/'
    | '/feed/'
    | '/products/'
    | '/__auth/sign-in/$'
    | '/feed/photo/$photoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DocsSplatRoute: typeof DocsSplatRoute
  PhotoPhotoIdRoute: typeof PhotoPhotoIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
  FeedIndexRoute: typeof FeedIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  _authSignInSplatRoute: typeof _authSignInSplatRoute
  FeedPhotoPhotoIdRoute: typeof FeedPhotoPhotoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/': {
      id: '/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$photoId': {
      id: '/photo/$photoId'
      path: '/photo/$photoId'
      fullPath: '/photo/$photoId'
      preLoaderRoute: typeof PhotoPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/photo/$photoId': {
      id: '/feed/photo/$photoId'
      path: '/feed/photo/$photoId'
      fullPath: '/feed/photo/$photoId'
      preLoaderRoute: typeof FeedPhotoPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/sign-in/$': {
      id: '/__auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof _authSignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DocsSplatRoute: DocsSplatRoute,
  PhotoPhotoIdRoute: PhotoPhotoIdRoute,
  DocsIndexRoute: DocsIndexRoute,
  FeedIndexRoute: FeedIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  _authSignInSplatRoute: _authSignInSplatRoute,
  FeedPhotoPhotoIdRoute: FeedPhotoPhotoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
