/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiDynamicRoutesUsersUserIdIndexRouteImport } from './routes/api/dynamic-routes/users/$userId/index'
import { Route as ApiDynamicRoutesUsersUserIdPostsPostIdRouteImport } from './routes/api/dynamic-routes/users/$userId/posts/$postId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDynamicRoutesUsersUserIdIndexRoute =
  ApiDynamicRoutesUsersUserIdIndexRouteImport.update({
    id: '/api/dynamic-routes/users/$userId/',
    path: '/api/dynamic-routes/users/$userId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDynamicRoutesUsersUserIdPostsPostIdRoute =
  ApiDynamicRoutesUsersUserIdPostsPostIdRouteImport.update({
    id: '/api/dynamic-routes/users/$userId/posts/$postId',
    path: '/api/dynamic-routes/users/$userId/posts/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/dynamic-routes/users/$userId/': typeof ApiDynamicRoutesUsersUserIdIndexRoute
  '/api/dynamic-routes/users/$userId/posts/$postId': typeof ApiDynamicRoutesUsersUserIdPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/dynamic-routes/users/$userId': typeof ApiDynamicRoutesUsersUserIdIndexRoute
  '/api/dynamic-routes/users/$userId/posts/$postId': typeof ApiDynamicRoutesUsersUserIdPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/dynamic-routes/users/$userId/': typeof ApiDynamicRoutesUsersUserIdIndexRoute
  '/api/dynamic-routes/users/$userId/posts/$postId': typeof ApiDynamicRoutesUsersUserIdPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/admin'
    | '/api/posts'
    | '/api/profile'
    | '/api/dynamic-routes/users/$userId/'
    | '/api/dynamic-routes/users/$userId/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/admin'
    | '/api/posts'
    | '/api/profile'
    | '/api/dynamic-routes/users/$userId'
    | '/api/dynamic-routes/users/$userId/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/admin'
    | '/api/posts'
    | '/api/profile'
    | '/api/dynamic-routes/users/$userId/'
    | '/api/dynamic-routes/users/$userId/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiPostsRoute: typeof ApiPostsRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiDynamicRoutesUsersUserIdIndexRoute: typeof ApiDynamicRoutesUsersUserIdIndexRoute
  ApiDynamicRoutesUsersUserIdPostsPostIdRoute: typeof ApiDynamicRoutesUsersUserIdPostsPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dynamic-routes/users/$userId/': {
      id: '/api/dynamic-routes/users/$userId/'
      path: '/api/dynamic-routes/users/$userId'
      fullPath: '/api/dynamic-routes/users/$userId/'
      preLoaderRoute: typeof ApiDynamicRoutesUsersUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dynamic-routes/users/$userId/posts/$postId': {
      id: '/api/dynamic-routes/users/$userId/posts/$postId'
      path: '/api/dynamic-routes/users/$userId/posts/$postId'
      fullPath: '/api/dynamic-routes/users/$userId/posts/$postId'
      preLoaderRoute: typeof ApiDynamicRoutesUsersUserIdPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiPostsRoute: ApiPostsRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiDynamicRoutesUsersUserIdIndexRoute: ApiDynamicRoutesUsersUserIdIndexRoute,
  ApiDynamicRoutesUsersUserIdPostsPostIdRoute:
    ApiDynamicRoutesUsersUserIdPostsPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
