/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypeSafeFeedbackRouteImport } from './routes/type-safe/feedback'
import { Route as RpcStatsRouteImport } from './routes/rpc/stats'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeSafeFeedbackRoute = TypeSafeFeedbackRouteImport.update({
  id: '/type-safe/feedback',
  path: '/type-safe/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcStatsRoute = RpcStatsRouteImport.update({
  id: '/rpc/stats',
  path: '/rpc/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rpc/stats': typeof RpcStatsRoute
  '/type-safe/feedback': typeof TypeSafeFeedbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rpc/stats': typeof RpcStatsRoute
  '/type-safe/feedback': typeof TypeSafeFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rpc/stats': typeof RpcStatsRoute
  '/type-safe/feedback': typeof TypeSafeFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/rpc/stats' | '/type-safe/feedback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/rpc/stats' | '/type-safe/feedback'
  id: '__root__' | '/' | '/about' | '/rpc/stats' | '/type-safe/feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RpcStatsRoute: typeof RpcStatsRoute
  TypeSafeFeedbackRoute: typeof TypeSafeFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type-safe/feedback': {
      id: '/type-safe/feedback'
      path: '/type-safe/feedback'
      fullPath: '/type-safe/feedback'
      preLoaderRoute: typeof TypeSafeFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/stats': {
      id: '/rpc/stats'
      path: '/rpc/stats'
      fullPath: '/rpc/stats'
      preLoaderRoute: typeof RpcStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RpcStatsRoute: RpcStatsRoute,
  TypeSafeFeedbackRoute: TypeSafeFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
