/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RouterCacheRouteImport } from './routes/router-cache'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileInvalidateRouteImport } from './routes/profile/invalidate'
import { Route as ApiProfileRouteImport } from './routes/api/profile'

const RouterCacheRoute = RouterCacheRouteImport.update({
  id: '/router-cache',
  path: '/router-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileInvalidateRoute = ProfileInvalidateRouteImport.update({
  id: '/profile/invalidate',
  path: '/profile/invalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/router-cache': typeof RouterCacheRoute
  '/api/profile': typeof ApiProfileRoute
  '/profile/invalidate': typeof ProfileInvalidateRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/router-cache': typeof RouterCacheRoute
  '/api/profile': typeof ApiProfileRoute
  '/profile/invalidate': typeof ProfileInvalidateRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/router-cache': typeof RouterCacheRoute
  '/api/profile': typeof ApiProfileRoute
  '/profile/invalidate': typeof ProfileInvalidateRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/router-cache'
    | '/api/profile'
    | '/profile/invalidate'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/router-cache'
    | '/api/profile'
    | '/profile/invalidate'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/router-cache'
    | '/api/profile'
    | '/profile/invalidate'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RouterCacheRoute: typeof RouterCacheRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ProfileInvalidateRoute: typeof ProfileInvalidateRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/router-cache': {
      id: '/router-cache'
      path: '/router-cache'
      fullPath: '/router-cache'
      preLoaderRoute: typeof RouterCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/invalidate': {
      id: '/profile/invalidate'
      path: '/profile/invalidate'
      fullPath: '/profile/invalidate'
      preLoaderRoute: typeof ProfileInvalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RouterCacheRoute: RouterCacheRoute,
  ApiProfileRoute: ApiProfileRoute,
  ProfileInvalidateRoute: ProfileInvalidateRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
